### ISSUE TITLE
Error on hydration when parent document field does not exist

### ISSUE THREAD

**Issue by antoscarface** [refugis/elastica-odm#4]
When a document has a parent as `null`, there is an error during hydration of documents after a search. Here the error:
```
ErrorException: Trying to get property 'name' of non-object in file /var/www/vendor/refugis/elastica-odm/src/Hydrator/ObjectHydrator.php on line 60

#0 /var/www/vendor/refugis/elastica-odm/src/Hydrator/ObjectHydrator.php(60): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/vendor...', 60, Array)
#1 [internal function]: Refugis\ODM\Elastica\Hydrator\ObjectHydrator::Refugis\ODM\Elastica\Hydrator\{closure}('join')
#2 /var/www/vendor/refugis/elastica-odm/src/Hydrator/ObjectHydrator.php(68): array_map(Object(Closure), Array)
#3 /var/www/vendor/refugis/elastica-odm/src/Search/Search.php(173): Refugis\ODM\Elastica\Hydrator\ObjectHydrator->hydrateAll(Object(Elastica\ResultSet), 'App\\Elastic\\Com...')
#4 [internal function]: Refugis\ODM\Elastica\Search\Search->getIterator()
#5 /var/www/vendor/refugis/elastica-odm/src/Search/Search.php(121): iterator_to_array(Object(Generator), false)
```

**Comment by alekitto** [comment]
Fixed on `master`
